# Generated by Django 5.1.3 on 2024-12-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reviews_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
