# Generated by Django 5.1.3 on 2024-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal'), ('Bank Transfer', 'Bank Transfer'), ('Cash on Delivery', 'Cash on Delivery'), ('bKash', 'bKash'), ('Rocket', 'Rocket'), ('Apple Pay', 'Apple Pay'), ('Google Pay', 'Google Pay'), ('Master Card', 'Master Card'), ('Nagad', 'Nagad')], default='Credit Card', max_length=50),
        ),
    ]
