# Generated by Django 5.1.3 on 2024-11-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingmethod',
            old_name='price',
            new_name='charge',
        ),
    ]
